### ISSUE TITLE
No identifiers allowed directly after numeric literal in Safari browser using build from WebPack

### ISSUE THREAD

**Issue by avral** [manh-vv/eosjs-name#11]
<img width="496" alt="Screenshot 2021-04-18 at 22 02 37" src="https://user-images.githubusercontent.com/10092436/115157435-c0dd7700-a0bb-11eb-85f4-88278b5f84f3.png">
After import this lib, i getting this errors in Safari

**Comment by manh-vv** [comment]
Thank @avral for reporting this. I will take a look at it.

**Comment by manh-vv** [comment]
@avral 

I've just tried:

- https://npm.runkit.com/eosjs-account-name
- https://manh-vv.github.io/eosjs-name/

in safari and there is no error.

Did you solve the problem?

**Comment by manh-vv** [comment]
btw, this lib uses `BigInt` which is supported by https://caniuse.com/?search=bigint.
